name: format
on: push
jobs:
  check-javascript-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Match local and CI version. I use version 16 because it's LTS.
          node-version: '16'
      - run: cd javascript
      - run: yarn install
      - run: yarn ci:format
